name: Validate Release Build

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Build Release Assets
      run: |
        docker buildx create --name container-builder --driver docker-container --use
        export RELEASE_TAG="$(git describe --tags --always)"
        ./build-docker-release.sh  release
        ./build-docker.sh

