name: Build Git for macOS

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-git:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Cache Git Source
      uses: actions/cache@v3
      with:
        path: src/git/.git
        key: git-src
        restore-keys: |
          git-src
    - name: Install Dependencies
      run: |
        brew update
        brew install autoconf
    - name: Build Git
      run: ./build-git.sh
    - name: Build installers
      run: ./build-pkgs.sh
    - name: Attach Build Files to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_ID=$(gh api repos/${{ github.repository }}/releases | jq -r '.[] | select(.draft == true) | .id')

        if [ -z "$RELEASE_ID" ]; then
          echo "No draft release found. Exiting."
          exit 1
        fi

        echo "Uploading build artifacts to release $RELEASE_ID"

        gh release upload "$RELEASE_ID" dist/git.pkg --clobber
        gh release upload "$RELEASE_ID" dist/git.tar.gz --clobber
        gh release upload "$RELEASE_ID" dist/git --clobber
        gh release upload "$RELEASE_ID" dist/gh --clobber
    - name: Save Git Source Cache
      uses: actions/cache@v3
      if: always() # Ensure cache is saved even if the build fails
      with:
        path: src/git/.git
        key: git-src
