name: Build Release Assets

on:
  release:
    types:
      - published
  workflow_dispatch:
permissions:
    contents: write
    packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build Release Assets
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        docker buildx create --name container-builder --driver docker-container --use
        export RELEASE_TAG="$(git describe --tags --always)"
        ./build-docker-release.sh --push release
        gh release upload --clobber "${RELEASE_TAG}" release/*

