name: Test Build

on:
  workflow_dispatch:
jobs:
  build-git:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Zsh
      run: |
        sudo apt-get update
        sudo apt-get install zsh
        zsh --version
    - name: Build installers
      run: |
        mkdir -p ./dist
        ./localpkg.zsh build @ dist/localpkg
